commons:
  sitename: Dame IE
  description: Internet Explorerから他のブラウザへの移行の促進を行うサイトです。
  year: 2019
  author: アルム＝バンド
  url: https://ieeenande.ewigleere.net/
  ogpimage: img/eyecatch.jpg
  twitteraccount: Bredtn_1et
  newsthumbnail: img/thumbnails/
  iel: <i class="fab fa-fw fa-internet-explorer" aria-hidden="true"></i>
  ielm: <i class="fab fa-fw fa-internet-explorer magni1_5" aria-hidden="true"></i>
  iet: Internet Explorer
param:
  indexcount: 6
  newscount: 6
  articlesns:
    twitter: true
    facebook: true
    googleplus: false
    line: true
    pocket: true
    feedly: true
