commons:
  sitename: Dame IE
  description: Microsoftから使用を止めるように要請が出された今こそーー今度こそ、完全なる眠りを、彼のIEへ。
  year: 2019
  author: アルム＝バンド
  url: https://ieeenande.ewigleere.net
  ogpimage: img/eyecatch.jpg
  twitteraccount: Bredtn_1et
  newsthumbnail: img/thumbnails/
  ie: <i class="fab fa-fw fa-internet-explorer" aria-hidden="true"></i>Internet Explorer
param:
  indexcount: 3
  newscount: 6
  articlesns:
    twitter: true
    facebook: true
    googleplus: false
    line: true
    pocket: true
    feedly: true
