functions:
    usephp: false
    news: true
    ssl: true
    democontents: true
ftp:
    user:
    password:
    host: test.example.com
    port: 21
    localRoot: ./dist/
    remoteRoot: ./path/to/web/root/
    include:
    - "*"
    - "**/*"
    exclude:
    - "daishi/**/*"
    deleteRemote: false